title: Product
type: object
x-examples:
  Example: {}
properties:
  id:
    type: string
    example: '0001'
  name:
    type: string
    example: Museum Tour With Lunch
  reference:
    type: string
    example: LR1
  description:
    type:
      - string
      - 'null'
    example: XXXX
  timeZone:
    type: string
    example: Europe/London
  availabilityType:
    type: string
    enum:
      - startTime
      - openingHours
    example: openingHours
  capabilities:
    type: array
    uniqueItems: true
    items:
      $ref: ./capability.v1.yaml
  options:
    type: array
    uniqueItems: true
    items:
      $ref: ./option.v1.yaml
